-- 1. Buat ENUM untuk Status (agar data konsisten)
CREATE TYPE validation_status_type AS ENUM ('PENDING', 'VALIDATED', 'REJECTED');
CREATE TYPE user_role_type AS ENUM ('admin', 'doctor');

-- 2. Buat Tabel USERS (Bisa di-link dengan Supabase Auth nantinya)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    role user_role_type DEFAULT 'doctor',
    status TEXT DEFAULT 'active', -- Active/Inactive
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. Buat Tabel PATIENTS
CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. Buat Tabel MEDICAL_RECORDS (Tabel Utama)
CREATE TABLE medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    validator_id BIGINT REFERENCES users(id), -- Dokter yang memvalidasi
    
    -- Data Awal (Upload Admin/System)
    original_image_path TEXT NOT NULL,
    ai_diagnosis TEXT, -- 'Malignant' / 'Benign'
    ai_gradcam_path TEXT,
    ai_confidence FLOAT,
    
    -- Data Validasi Dokter (Update)
    doctor_diagnosis TEXT,
    doctor_brush_path TEXT, -- Path ke file gambar coretan
    doctor_notes TEXT,
    is_ai_accurate BOOLEAN,
    
    -- Status Flag
    validation_status validation_status_type DEFAULT 'PENDING',
    
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    validated_at TIMESTAMP WITH TIME ZONE
);

-- 5. Buat Tabel ACTIVITY_LOGS
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    action_type TEXT,
    description TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);